inherit_from: "~CV-Project4/BRPO/configs/mono/waymo/base_config.yaml"

Dataset:
  dataset_path: "~CV-Project4/datasets/405841/FRONT"
  Calibration:
    fx: 2066.697564417299
    fy: 2066.697564417299
    cx: 950.5512774150723
    cy: 641.1870541472169
    k1: 0.036260226499726975
    k2: -0.35323300768499216
    p1: 0.0003256378403347263
    p2: 0.00021755891240936618
    k3: 0
    width: 1920
    height: 1280
    depth_scale: 5000.0
    distorted: True

Results:
  save_dir: "~CV-Project4/results/405841/"
  color_refinement: True

opt_params:
  position_lr_init: 0.0016
  position_lr_final: 0.00016
  init_lr: 6

Training:
  alpha: 0.98
  mapping_itr_nosingle: 30
  kf_interval: 10
  
  # Pseudo-view pose / coarse render
  pseudo_views_per_pair: 5
  pseudo_min_valid_ratio: 0.005

  # Difix3D / bidirectional restoration
  pseudo_refine_iters: 5
  difix_height: 512
  difix_width: 512
  difix_prompt: "preserve color and geometry"
  difix_timestep: 120

  # Looser overlap fusion / confidence filtering
  pseudo_use_reprojection: true
  pseudo_reproj_depth_tol: 0.35
  pseudo_corr_threshold: 0.02
  pseudo_overlap_threshold: 0.02
  pseudo_match_size: 512
  pseudo_match_subsample: 4
  pseudo_match_radius: 3
  pseudo_opacity_threshold: 0.20

  # Backend pseudo optimization: looser mask, but safer optimization
  pseudo_pose_stabilize_iters: 0
  pseudo_joint_iters: 5

  optimize_pseudo_pose: false
  optimize_pseudo_exposure: true

  pseudo_pose_lr_rot: 0.00001
  pseudo_pose_lr_trans: 0.00001
  pseudo_exposure_lr_a: 0.0005
  pseudo_exposure_lr_b: 0.0005

  lambda_pseudo: 0.005
  pseudo_rgbd_beta: 0.99
  pseudo_depth_decay: 1.0
  lambda_pseudo_scale: 0.0001

  lambda_pseudo_pose_reg: 0.005
  pseudo_pose_max_rot_delta: 0.0001
  pseudo_pose_max_trans_delta: 0.0001

  pseudo_use_lowfreq_align: false
