inherit_from: "/data/yywong558/CV_PROJECT/S3PO-GS/configs/mono/dl3dv/base_config.yaml"

Dataset:
  type: 'dl3dv'
  dataset_path: "~/CV-Project4/datasets/DL3DV-2"
  begin: 0
  end: 300
  Calibration:
    fx: 204.04736
    fy: 204.08832
    cx: 128.0
    cy: 128.0
    k1: 0.0
    k2: 0.0
    p1: 0.0
    p2: 0.0
    k3: 0.0
    width: 256
    height: 256
    depth_scale: 200.0
    distorted: False

Results:
  save_dir: "/data/yywong558/CV_PROJECT/part2/results/DL3DV-2/pipeline_refinement"
  color_refinement: True

opt_params:
  position_lr_init: 0.0016
  position_lr_final: 0.0000016
  init_lr: 6

Training:
  mapping_itr_nosingle: 10
  kf_interval: 30
